### ISSUE TITLE
Can this be used as a primary key?

### ISSUE THREAD

**Issue by littlepea** [ivelum/django-uidfield#3]
For example, right now I'm doing the following:

```python
import uuid
from django.db import models

class YourModel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
```

Would it make sense to?

```python
from django.db import models
from django_uidfield.fields import UIDField

class YourModel(models.Model):
    id = UIDField(primary_key=True, editable=False, max_length=20)
```

**Comment by iceone** [comment]
Sure, see the appropriate test: https://github.com/ivelum/django-uidfield/blob/master/django_uidfield/tests.py#L41-L47

**Comment by littlepea** [comment]
I mean more not "is it technically possible" but is it a good idea? :)

Is there any advantage of using `django-uidfield` vs `UUIDField` from `django.models`?
